//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBibleThump.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOYABAZAEntities : DbContext
    {
        public MOYABAZAEntities()
            : base("name=MOYABAZAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Авторы> Авторы { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<Издательства> Издательства { get; set; }
        public virtual DbSet<Книги> Книги { get; set; }
        public virtual DbSet<Объекты> Объекты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Пользователи_Объекты> Пользователи_Объекты { get; set; }
        public virtual DbSet<Систематический_каталог> Систематический_каталог { get; set; }
        public virtual DbSet<Улицы> Улицы { get; set; }
        public virtual DbSet<Читатели> Читатели { get; set; }
        public virtual DbSet<Экземпляры_книги> Экземпляры_книги { get; set; }
        public virtual DbSet<Выданные_книги> Выданные_книги { get; set; }
    }
}
