//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBibleThump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи_Объекты
    {
        public int Id_User { get; set; }
        public int Id_Object { get; set; }
        public short R { get; set; }
        public short W { get; set; }
        public short E { get; set; }
        public short D { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
