
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WPFBibleThump.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Пользователи
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Пользователи()
    {

        this.Пользователи_Объекты = new HashSet<Пользователи_Объекты>();

    }


    public int Id { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Пользователи_Объекты> Пользователи_Объекты { get; set; }

}

}
