//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBibleThump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Читатели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Читатели()
        {
            this.Выданные_книги = new HashSet<Выданные_книги>();
        }
    
        public int Id { get; set; }
        public string Номер_читательского_билета { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public int Id_улицы { get; set; }
        public string Номер_дома { get; set; }
        public string Квартира { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public Nullable<System.DateTime> Дата_перерегистрации { get; set; }
    
        public virtual Улицы Улицы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выданные_книги> Выданные_книги { get; set; }
    }
}
